python cacheSim2.py -f Corruption2.trc -s 4 -b 4 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 4 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 4 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 4 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 4 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 8 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 8 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 8 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 8 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 8 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 16 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 16 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 16 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 16 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 16 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 32 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 32 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 32 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 32 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 32 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 64 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 64 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 64 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 64 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 4 -b 64 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 4 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 4 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 4 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 4 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 4 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 8 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 8 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 8 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 8 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 8 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 16 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 16 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 16 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 16 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 16 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 32 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 32 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 32 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 32 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 32 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 64 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 64 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 64 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 64 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 8 -b 64 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 4 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 4 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 4 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 4 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 4 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 8 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 8 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 8 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 8 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 8 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 16 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 16 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 16 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 16 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 16 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 32 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 32 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 32 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 32 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 32 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 64 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 64 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 64 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 64 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 16 -b 64 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 4 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 4 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 4 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 4 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 4 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 8 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 8 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 8 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 8 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 8 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 16 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 16 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 16 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 16 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 16 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 32 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 32 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 32 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 32 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 32 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 64 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 64 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 64 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 64 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 32 -b 64 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 4 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 4 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 4 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 4 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 4 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 8 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 8 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 8 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 8 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 8 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 16 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 16 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 16 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 16 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 16 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 32 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 32 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 32 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 32 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 32 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 64 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 64 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 64 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 64 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 64 -b 64 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 4 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 4 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 4 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 4 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 4 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 8 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 8 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 8 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 8 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 8 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 16 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 16 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 16 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 16 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 16 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 32 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 32 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 32 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 32 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 32 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 64 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 64 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 64 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 64 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 128 -b 64 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 4 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 4 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 4 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 4 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 4 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 8 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 8 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 8 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 8 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 8 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 16 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 16 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 16 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 16 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 16 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 32 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 32 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 32 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 32 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 32 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 64 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 64 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 64 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 64 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 256 -b 64 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 4 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 4 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 4 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 4 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 4 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 8 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 8 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 8 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 8 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 8 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 16 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 16 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 16 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 16 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 16 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 32 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 32 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 32 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 32 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 32 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 64 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 64 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 64 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 64 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 512 -b 64 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 4 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 4 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 4 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 4 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 4 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 8 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 8 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 8 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 8 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 8 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 16 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 16 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 16 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 16 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 16 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 32 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 32 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 32 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 32 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 32 -a 16 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 64 -a 1 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 64 -a 2 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 64 -a 4 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 64 -a 8 -r RR >> sim.cvs
python cacheSim2.py -f Corruption2.trc -s 1024 -b 64 -a 16 -r RR >> sim.cvs
